### PR TITLE
Completely Updated

### PR DESCRIPTION
**Pull request by nasirhm**
I updated the exercise 4 readme.md file by adding the installation of vim.

### CODE REVIEW

**Review by mohuk — CHANGES_REQUESTED** [review]
This PR is incorrect, I just verified running `httpd:alpine` and it has `vi` installed. Also, `apt-get` doesn't work on `alpine`.

Steps:
1) `docker run -it httpd:alpine bash`
2) `vi`

Above works

**Comment by nasirhm** [comment]
Ok but whats the package installer for alpine

**Comment by mashhoodr** [comment]
@nasirhm lets close this if we dont need it any more?

**Comment by nasirhm** [comment]
@mashhoodr  Sorry for this Forgot to Close

**Pull request closed without merging**
